# Generated by Django 4.1.5 on 2023-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=30)),
                ("info", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
